name: Full CI Tests

on:
  push:
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: backend/node_modules
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-backend-${{ hashFiles('backend/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-backend-

      - name: Install dependencies
        working-directory: backend
        run: yarn install --frozen-lockfile

      - name: Run tests
        working-directory: backend
        run: yarn test
