name: Full CI Tests

on:
  push:
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: cd backend && yarn install --frozen-lockfile

      - name: Run tests
        run: cd backend && yarn test
